spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb
      database: userdb
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: yash
#    password: yash
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
