spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true

#Logging:
#  level:
#    root: INFO
#    com.ecommerce.user: TRACE
#  file:
#    name: logs/userServiceLogs/${spring.application.name}.log
#  logback:
#    rollingpolicy:
#      max-file-size: 5MB
#      max-history: 7