server:
  port: 8084

spring:
  application:
    name: notification
  cloud:
    bus:
      destination: springCloudBus
    function:
      definition: orderCreated
    stream:
      function:
        definition: orderCreated
      bindings:
        orderCreated-in-0:
          destination: order.exchange.new
          group: notification-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
#          destination: order.exchange.new
      #        springCloudBusInput:
      #          group: order-service-group

#  rabbitmq:
#    host: ${RABBITMQ_HOST:localhost}
#    port: ${RABBITMQ_PORT:5672}
#    username: ${RABBITMQ_USERNAME:guest}
#    password: ${RABBITMQ_PASSWORD:guest}
#    VIRTUAL-HOST: ${RABBITMQ_VHOST:guest}
#    connection-timeout: 30000


#rabbitmq:
#  exchange:
#    name: order.exchange
#  queue:
#    name: order.queue
#  routing:
#    key: order.tracking