spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: yash
    password: yash
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083
