server:
  port: 8080

spring:
  main:
    web-application-type: reactive

management:
  endpoint:
    gateway:
      access: unrestricted
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

#logging:
#  level:
    #    root: INFO
    #    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#    org.springframework.cloud.gateway: TRACE

# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      ecomBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based