spring:
  application:
    name: configserver
  profiles:
    active: native


  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\PreprationCodes\SpringBootMicroservices\Microservices\Ecommerce-Microservice\configserver\src\main\resources\config
#          search-locations: classpath:/config
    bus:
      enabled: true
      destination: springCloudBus

    stream:
      bindings:
        springCloudBusInput:
          group: config-server-group

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    VIRTUAL-HOST: ${RABBITMQ_VHOST:guest}
    connection-timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888

# configuration to connect to git hub
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/<user>/<repo-name>
